### ISSUE TITLE
startActivityForResult() is deprecated

### ISSUE THREAD

**Issue by Okisthisavailable** [MahakAggarwal/Android-Developer-Fundamentals-Version-2#3]
The used Method startActivityForResult() is deprecated, and the documentation for the recommended new way leaves me utterly confused. I would appreciate an update very much!

**Comment by MahakAggarwal** [comment]
I will leave an answer here -
When referring to Main Activity at the URL - [https://github.com/MahakAggarwal/Android-Developer-Fundamentals-Version-2/tree/master/2.1_Activities_and_intents/TwoActivities/app/src/main/java/me/mahakagg/twoactivities](https://github.com/MahakAggarwal/Android-Developer-Fundamentals-Version-2/tree/master/2.1_Activities_and_intents/TwoActivities/app/src/main/java/me/mahakagg/twoactivities)

In the method launchSecondActivity(View view) - 

Comment out this method as it is deprecated - 
`public void onActivityResult(int requestCode, int resultCode, Intent data){...}`

Replace this line
`startActivityForResult(intent, TEXT_REQUEST);`

with this line
`secondActivityResultLauncher.launch(intent)`. The method secondActivityResultLauncher is defined below -

```
// replace the commented out method with the following
ActivityResultLauncher<Intent> secondActivityResultLauncher = registerForActivityResult(
     new ActivityResultContracts.StartActivityForResult(),
     new ActivityResultCallback<ActivityResult>() {
              @Override
              public void onActivityResult(ActivityResult result) {
                   if (result.getResultCode() == Activity.RESULT_OK) {
                         Intent data = result.getData();
                         String reply = data.getStringExtra(SecondActivity.EXTRA_REPLY);
                         mReplyHeadTextView.setVisibility(View.VISIBLE);
                         mReplyTextView.setVisibility(View.VISIBLE);
                         mReplyTextView.setText(reply);
                    }
               }
      });
```

In the new piece of code, `registerForActivityResult` takes 2 lambda methods as parameters - `ActivityResultContracts` which define the input type needed for the result and the output type as well (you can call this a contract). You can find a list of these contracts along with the input and output types at [https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts](https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts).
The second lambda parameter `ActivityResultCallback` is triggered when the other activity returns a result. The output type of `ActivityResultContracts` is taken as the parameter for this (in the angular brackets, as well as `onActivityResult`), which in this case is `ActivityResult`. So the input type here is an intent while the output type is `ActivityResult`. When `secondActivityResultLauncher.launch(intent)` is called, it will take you to the second activity and once the results are processed there and sent back to main activity, `onActivityResult` will be called.

**Comment by MahakAggarwal** [comment]
If you are starting out with android development, I strongly recommend that you use Kotlin instead of Java for Android development. The code is easier to understand, there will be less room for error, and Google is using it for the latest android technologies such as Jetpack Compose.
As a developer myself, I saw a lot fewer errors in production-ready code when using Kotlin instead of Java.

**Comment by Okisthisavailable** [comment]
Thank you for the quick answers. Code works flawlessly, additional explaination is very much appreciated!
